# Notebook 01

# Filtración de datos

#### Importación de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Carga del dataset

In [2]:
df = pd.read_csv('dataset_PetFinder.csv')

#### Estructura del dataset

In [3]:
df.shape

(14993, 24)

In [4]:
df.head()

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,...,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,...,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,...,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Type           14993 non-null  int64
 1   Name           13736 non-null  object
 2   Age            14993 non-null  int64
 3   Breed1         14993 non-null  int64
 4   Breed2         14993 non-null  int64
 5   Gender         14993 non-null  int64
 6   Color1         14993 non-null  int64
 7   Color2         14993 non-null  int64
 8   Color3         14993 non-null  int64
 9   MaturitySize   14993 non-null  int64
 10  FurLength      14993 non-null  int64
 11  Vaccinated     14993 non-null  int64
 12  Dewormed       14993 non-null  int64
 13  Sterilized     14993 non-null  int64
 14  Health         14993 non-null  int64
 15  Quantity       14993 non-null  int64
 16  Fee            14993 non-null  int64
 17  State          14993 non-null  int64
 18  RescuerID      14993 non-null  object
 19  VideoAmt       14993 non-null  int64
 20  Description    14981 non-null  object
 21  PetID          14993 non-null  object
 22  PhotoAmt       14993 non-null  float64
 23  AdoptionSpeed  14993 non-null  int64
dtypes: float64(1), int64(19), object(4)
memory usage: 2.7+ MB

#### Filtrado de registros, Type = 2 (gatos)

In [6]:
df_gatos = df[df["Type"] == 2].copy()

In [7]:
df_gatos.shape

(6861, 24)

In [8]:
df_gatos["Type"].value_counts()

2    6861
Name: Type, dtype: int64

In [9]:
df_gatos.drop(columns="Type", inplace=True)

#### Renombramiento de columnas y exportación de csv

In [10]:
df_gatos = df_gatos.rename(columns={
    "Name": "Nombre",
    "Age": "Edad_Meses",
    "Breed1": "Raza_Principal",
    "Breed2": "Raza_Secundaria",
    "Gender": "Genero",
    "Color1": "Color_Principal",
    "Color2": "Color_Secundario",
    "Color3": "Color_Terciario",
    "MaturitySize": "Tamano_Madurez",
    "FurLength": "Longitud_Pelo",
    "Vaccinated": "Vacunado",
    "Dewormed": "Desparasitado",
    "Sterilized": "Esterilizado",
    "Health": "Salud",
    "Quantity": "Cantidad",
    "Fee": "Cuota_Adopcion",
    "State": "Estado",
    "RescuerID": "ID_Rescatista",
    "VideoAmt": "Cantidad_Videos",
    "Description": "Descripcion",
    "PetID": "ID_Mascota",
    "PhotoAmt": "Cantidad_Fotos",
    "AdoptionSpeed": "Velocidad_Adopcion"
})

In [11]:
df_gatos.to_csv("dataset_gatos.csv",index=False,encoding="utf-8-sig")

### Revisión de la estructura del dataset gatos

In [12]:
df_gatos.head()

,Nombre,Edad_Meses,Raza_Principal,Raza_Secundaria,Genero,Color_Principal,Color_Secundario,Color_Terciario,Tamano_Madurez,Longitud_Pelo,...,Salud,Cantidad,Cuota_Adopcion,Estado,ID_Rescatista,Cantidad_Videos,Descripcion,ID_Mascota,Cantidad_Fotos,Velocidad_Adopcion
0,Nibble,3,299,0,1,1,7,0,1,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,No Name Yet,1,265,0,1,1,2,0,2,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
5,NaN,3,266,0,2,5,6,0,2,1,...,1,1,0,41326,22fe332bf9c924d4718005891c63fbed,0,This is a stray kitten that came to my house. ...,d24c30b4b,2.0,2
6,BULAT,12,264,264,1,1,0,0,2,3,...,1,1,300,41326,1e0b5a458b5b77f5af581d57ebf570b3,0,anyone within the area of ipoh or taiping who ...,1caa6fcdb,3.0,1
8,NaN,2,265,0,2,6,0,0,2,2,...,1,1,0,41326,d8af7afece71334473575c9f70daf00d,0,"healthy and active, feisty kitten found in nei...",c06d167ca,6.0,1

In [13]:
df_gatos.shape

(6861, 23)

In [14]:
df_gatos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6861 entries, 0 to 14991
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Nombre              6253 non-null   object
 1   Edad_Meses          6861 non-null   int64
 2   Raza_Principal      6861 non-null   int64
 3   Raza_Secundaria     6861 non-null   int64
 4   Genero              6861 non-null   int64
 5   Color_Principal     6861 non-null   int64
 6   Color_Secundario    6861 non-null   int64
 7   Color_Terciario     6861 non-null   int64
 8   Tamano_Madurez      6861 non-null   int64
 9   Longitud_Pelo       6861 non-null   int64
 10  Vacunado            6861 non-null   int64
 11  Desparasitado       6861 non-null   int64
 12  Esterilizado        6861 non-null   int64
 13  Salud               6861 non-null   int64
 14  Cantidad            6861 non-null   int64
 15  Cuota_Adopcion      6861 non-null   int64
 16  Estado              6861 non-null   int64
 17  ID_Rescatista       6861 non-null   object
 18  Cantidad_Videos     6861 non-null   int64
 19  Descripcion         6852 non-null   object
 20  ID_Mascota          6861 non-null   object
 21  Cantidad_Fotos      6861 non-null   float64
 22  Velocidad_Adopcion  6861 non-null   int64
dtypes: float64(1), int64(18), object(4)
memory usage: 1.3+ MB

In [15]:
df_gatos.describe()

,Edad_Meses,Raza_Principal,Raza_Secundaria,Genero,Color_Principal,Color_Secundario,Color_Terciario,Tamano_Madurez,Longitud_Pelo,Vacunado,Desparasitado,Esterilizado,Salud,Cantidad,Cuota_Adopcion,Estado,Cantidad_Videos,Cantidad_Fotos,Velocidad_Adopcion
count,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000,6861.000000
mean,7.543361,269.046640,68.175193,1.821309,2.419764,3.958315,2.537239,1.759510,1.469465,1.806005,1.578050,1.918379,1.035126,1.634456,17.663169,41350.427489,0.054511,4.076665,2.399504
std,12.771554,14.209506,117.924234,0.726119,1.892870,2.680185,3.232753,0.581442,0.615264,0.590843,0.650796,0.527701,0.194132,1.390996,61.603234,34.453207,0.323432,3.490296,1.205065
min,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,41324.000000,0.000000,0.000000,0.000000
25%,2.000000,265.000000,0.000000,1.000000,1.000000,2.000000,0.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,0.000000,41326.000000,0.000000,2.000000,1.000000
50%,3.000000,266.000000,0.000000,2.000000,1.000000,4.000000,0.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000,41326.000000,0.000000,3.000000,2.000000
75%,8.000000,266.000000,241.000000,2.000000,3.000000,7.000000,7.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,0.000000,41401.000000,0.000000,5.000000,4.000000
max,212.000000,307.000000,306.000000,3.000000,7.000000,7.000000,7.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,20.000000,800.000000,41415.000000,6.000000,30.000000,4.000000

#### Casting semántico

In [16]:
# Casting de variables de texto
columnas_texto = ["Descripcion","ID_Rescatista","ID_Mascota"]
df_gatos[columnas_texto] = df_gatos[columnas_texto].astype("string")

# Casting de variables numéricas
df_gatos["Edad_Meses"] = df_gatos["Edad_Meses"].astype("int16")
df_gatos["Cantidad"] = df_gatos["Cantidad"].astype("int8")
df_gatos["Cuota_Adopcion"] = df_gatos["Cuota_Adopcion"].astype("int16")
df_gatos["Cantidad_Videos"] = df_gatos["Cantidad_Videos"].astype("int8")

# Cantidad_Fotos puede contener NA, por eso usamos Int8 (nullable)
df_gatos["Cantidad_Fotos"] = df_gatos["Cantidad_Fotos"].astype("Int8")

# Casting de variables categóricas
columnas_categoria = [
    "Genero",
    "Tamano_Madurez",
    "Longitud_Pelo",
    "Vacunado",
    "Desparasitado",
    "Esterilizado",
    "Salud"
]

for col in columnas_categoria:
    df_gatos[col] = df_gatos[col].astype("category")

print("Casting realizado correctamente.")
df_gatos.info()

Casting realizado correctamente.
<class 'pandas.core.frame.DataFrame'>
Int64Index: 6861 entries, 0 to 14991
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Nombre              6253 non-null   object
 1   Edad_Meses          6861 non-null   int16
 2   Raza_Principal      6861 non-null   int64
 3   Raza_Secundaria     6861 non-null   int64
 4   Genero              6861 non-null   category
 5   Color_Principal     6861 non-null   int64
 6   Color_Secundario    6861 non-null   int64
 7   Color_Terciario     6861 non-null   int64
 8   Tamano_Madurez      6861 non-null   category
 9   Longitud_Pelo       6861 non-null   category
 10  Vacunado            6861 non-null   category
 11  Desparasitado       6861 non-null   category
 12  Esterilizado        6861 non-null   category
 13  Salud               6861 non-null   category
 14  Cantidad            6861 non-null   int8
 15  Cuota_Adopcion      6861 non-null   int16
 16  Estado              6861 non-null   int64
 17  ID_Rescatista       6861 non-null   string
 18  Cantidad_Videos     6861 non-null   int8
 19  Descripcion         6852 non-null   string
 20  ID_Mascota          6861 non-null   string
 21  Cantidad_Fotos      6861 non-null   Int8
 22  Velocidad_Adopcion  6861 non-null   int64
dtypes: Int8(1), category(7), int16(2), int64(7), int8(2), object(1), string(3)
memory usage: 744.7+ KB

#### Etiquetar categorías

In [17]:
df_gatos["Genero"] = df_gatos["Genero"].cat.rename_categories({
    1: "Macho",
    2: "Hembra",
    3: "Mixto"
})

In [18]:
df_gatos["Tamano_Madurez"] = df_gatos["Tamano_Madurez"].cat.rename_categories({
    0: "No especificado",
    1: "Pequeño",
    2: "Mediano",
    3: "Grande",
    4: "Extra grande"
})

In [19]:
df_gatos["Longitud_Pelo"] = df_gatos["Longitud_Pelo"].cat.rename_categories({
    0: "No especificado",
    1: "Corto",
    2: "Medio",
    3: "Largo"
})

In [20]:
dic_si_no = {
    1: "Sí",
    2: "No",
    3: "No seguro"
}

df_gatos["Vacunado"] = df_gatos["Vacunado"].cat.rename_categories(dic_si_no)
df_gatos["Desparasitado"] = df_gatos["Desparasitado"].cat.rename_categories(dic_si_no)
df_gatos["Esterilizado"] = df_gatos["Esterilizado"].cat.rename_categories(dic_si_no)

In [21]:
df_gatos["Salud"] = df_gatos["Salud"].cat.rename_categories({
    0: "No especificado",
    1: "Sano",
    2: "Lesión leve",
    3: "Lesión grave"
})

In [22]:
# Etiquetar velocidad de adopción
mapa_velocidad = {
    0: "Mismo día",
    1: "1–7 días",
    2: "8–30 días",
    3: "31–90 días",
    4: "No adoptado (+100 días)"
}

df_gatos["Velocidad_Adopcion_Nombre"] = (df_gatos["Velocidad_Adopcion"].map(mapa_velocidad))

#### Validación después del casting

In [23]:
# Resumen de tipos de datos
resumen_tipos = pd.DataFrame({
    "Tipo_Dato": df_gatos.dtypes.astype(str),
    "Valores_Unicos": df_gatos.nunique()
})

display(resumen_tipos)

                          Tipo_Dato  Valores_Unicos
Nombre                       object            4688
Edad_Meses                    int16              72
Raza_Principal                int64              68
Raza_Secundaria               int64              55
Genero                     category               3
Color_Principal               int64               7
Color_Secundario              int64               7
Color_Terciario               int64               6
Tamano_Madurez             category               4
Longitud_Pelo              category               3
Vacunado                   category               3
Desparasitado              category               3
Esterilizado               category               3
Salud                      category               3
Cantidad                       int8              18
Cuota_Adopcion                int16              51
Estado                        int64              14
ID_Rescatista                string            2947
Cantidad_Videos                int8               7
Descripcion                  string            6642
ID_Mascota                   string            6861
Cantidad_Fotos                 Int8              31
Velocidad_Adopcion            int64               5
Velocidad_Adopcion_Nombre    object               5

#### Revisión de datos nulos y duplicados

In [24]:
df_gatos.isnull().sum()

Nombre                       608
Edad_Meses                     0
Raza_Principal                 0
Raza_Secundaria                0
Genero                         0
Color_Principal                0
Color_Secundario               0
Color_Terciario                0
Tamano_Madurez                 0
Longitud_Pelo                  0
Vacunado                       0
Desparasitado                  0
Esterilizado                   0
Salud                          0
Cantidad                       0
Cuota_Adopcion                 0
Estado                         0
ID_Rescatista                  0
Cantidad_Videos                0
Descripcion                    9
ID_Mascota                     0
Cantidad_Fotos                 0
Velocidad_Adopcion             0
Velocidad_Adopcion_Nombre      0
dtype: int64

In [25]:
duplicados = df_gatos.duplicated().sum()

print(f"Registros duplicados: {duplicados}")

Registros duplicados: 0

#### Revisión de categorías

En esta sección se revisan las variables categóricas del conjunto de datos para conocer los valores presentes, su frecuencia y detectar posibles categorías "No especificado" antes del proceso de limpieza.

In [26]:
# Verificar resultado
df_gatos[
    ["Velocidad_Adopcion", "Velocidad_Adopcion_Nombre"]
].drop_duplicates().sort_values("Velocidad_Adopcion")

    Velocidad_Adopcion Velocidad_Adopcion_Nombre
1                    0                 Mismo día
6                    1                  1–7 días
0                    2                 8–30 días
16                   3                31–90 días
9                    4   No adoptado (+100 días)

In [27]:
# Lista de variables categóricas codificadas
columnas_categoricas = [
    "Genero",
    "Tamano_Madurez",
    "Longitud_Pelo",
    "Vacunado",
    "Desparasitado",
    "Esterilizado",
    "Salud",
    "Velocidad_Adopcion_Nombre"
]

print("="*60)
print("REVISIÓN DE CATEGORÍAS DEL DATASET PETFINDER (GATOS)")
print("="*60)

for columna in columnas_categoricas:
    print(f"\n 🔶 Variable: {columna}")
    print("-"*60)

    categorias = (df_gatos[columna].value_counts(dropna=False).sort_index().rename("Frecuencia").to_frame())

    categorias["Porcentaje (%)"] = (categorias["Frecuencia"] / len(df_gatos) * 100).round(2)
    display(categorias)

============================================================
REVISIÓN DE CATEGORÍAS DEL DATASET PETFINDER (GATOS)
============================================================

 🔶 Variable: Genero
------------------------------------------------------------

        Frecuencia  Porcentaje (%)
Macho         2531           36.89
Hembra        3025           44.09
Mixto         1305           19.02

 🔶 Variable: Tamano_Madurez
------------------------------------------------------------

              Frecuencia  Porcentaje (%)
Pequeño             2172           31.66
Mediano             4178           60.89
Grande               500            7.29
Extra grande          11            0.16

 🔶 Variable: Longitud_Pelo
------------------------------------------------------------

       Frecuencia  Porcentaje (%)
Corto        4084           59.52
Medio        2333           34.00
Largo         444            6.47

 🔶 Variable: Vacunado
------------------------------------------------------------

           Frecuencia  Porcentaje (%)
Sí               1992           29.03
No               4208           61.33
No seguro         661            9.63

 🔶 Variable: Desparasitado
------------------------------------------------------------

           Frecuencia  Porcentaje (%)
Sí               3511           51.17
No               2734           39.85
No seguro         616            8.98

 🔶 Variable: Esterilizado
------------------------------------------------------------

           Frecuencia  Porcentaje (%)
Sí               1258           18.34
No               4905           71.49
No seguro         698           10.17

 🔶 Variable: Salud
------------------------------------------------------------

              Frecuencia  Porcentaje (%)
Sano                6633           96.68
Lesión leve          215            3.13
Lesión grave          13            0.19

 🔶 Variable: Velocidad_Adopcion_Nombre
------------------------------------------------------------

                         Frecuencia  Porcentaje (%)
1–7 días                       1655           24.12
31–90 días                     1310           19.09
8–30 días                      1873           27.30
Mismo día                       240            3.50
No adoptado (+100 días)        1783           25.99

### Revisión de rangos

En esta sección se analizan las variables numéricas del conjunto de datos para identificar sus rangos, valores mínimos y máximos, posibles valores atípicos y distribuciones generales.

In [28]:
variables_numericas = [
    "Edad_Meses",
    "Cantidad",
    "Cuota_Adopcion",
    "Cantidad_Fotos",
    "Cantidad_Videos"
]

estadisticas = df_gatos[variables_numericas].describe().T
estadisticas = estadisticas[["count","mean","std","min","25%","50%","75%","max"]].round(2)
display(estadisticas)

                  count       mean        std  min  25%  50%  75%    max
Edad_Meses       6861.0   7.543361  12.771554  0.0  2.0  3.0  8.0  212.0
Cantidad         6861.0   1.634456   1.390996  1.0  1.0  1.0  2.0   20.0
Cuota_Adopcion   6861.0  17.663169  61.603234  0.0  0.0  0.0  0.0  800.0
Cantidad_Fotos   6861.0   4.076665   3.490296  0.0  2.0  3.0  5.0   30.0
Cantidad_Videos  6861.0   0.054511   0.323432  0.0  0.0  0.0  0.0    6.0

In [29]:
resumen_rangos = pd.DataFrame({
    "Mínimo": df_gatos[variables_numericas].min(),
    "Máximo": df_gatos[variables_numericas].max(),
    "Valores únicos": df_gatos[variables_numericas].nunique()
})

display(resumen_rangos)

                 Mínimo  Máximo  Valores únicos
Edad_Meses            0     212              72
Cantidad              1      20              18
Cuota_Adopcion        0     800              51
Cantidad_Fotos        0      30              31
Cantidad_Videos       0       6               7

### Tratamiento a datos nulos

In [30]:
print(f"Nombres nulos: {df_gatos['Nombre'].isna().sum()}")

Nombres nulos: 608

In [31]:
nombres_nulos = df_gatos[df_gatos["Nombre"].isna()]
print(f"Total de registros sin nombre: {len(nombres_nulos)}")
display(
    nombres_nulos[
        ["ID_Mascota", "Edad_Meses", "Genero", "Raza_Principal",
         "Estado", "Cantidad_Fotos", "Descripcion","Nombre"]
    ].head(10)
)

Total de registros sin nombre: 608

,ID_Mascota,Edad_Meses,Genero,Raza_Principal,Estado,Cantidad_Fotos,Descripcion,Nombre
5,d24c30b4b,3,Hembra,266,41326,2,This is a stray kitten that came to my house. ...,NaN
8,c06d167ca,2,Hembra,265,41326,6,"healthy and active, feisty kitten found in nei...",NaN
19,b10e7605a,1,Mixto,266,41326,1,"Birth Date: Oct 30th Kitty 1, Melly -Female Sa...",NaN
33,9415bc79e,4,Hembra,266,41326,7,Two gorgeous kittens have just lost their mumm...,NaN
36,61fa73996,24,Hembra,265,41326,2,she fat n healthy. in door cat,NaN
66,e540c1ba5,3,Hembra,266,41324,1,She needs a loving and caring home...,NaN
99,0f24b6cd6,3,Macho,265,41326,1,owner desert them.....,NaN
100,49bb70e36,1,Mixto,264,41401,1,These kittens were found in neighbourhood. Ple...,NaN
108,4407e70f3,2,Hembra,266,41401,2,"10 weeks old cute female kitty, lovable, cuddl...",NaN
115,1104fe6bb,1,Mixto,265,41326,2,young and playful. love to run around and very...,NaN

In [32]:
df_gatos["Nombre"] = (df_gatos["Nombre"].fillna("Sin nombre").str.strip())

In [33]:
descripcion_nula = df_gatos[df_gatos["Descripcion"].isna()]
print(f"Descripciones nulas: {len(descripcion_nula)}")
display(descripcion_nula[["ID_Mascota", "Nombre", "Edad_Meses","Genero", "Raza_Principal", "Cantidad_Fotos"]])

Descripciones nulas: 9

,ID_Mascota,Nombre,Edad_Meses,Genero,Raza_Principal,Cantidad_Fotos
96,5e4154870,Manja,19,Hembra,285,3
605,56583003c,Mickey,2,Macho,264,3
1098,8c4c4bc6e,Pucci,6,Macho,266,1
4218,9d82e4438,Mog,84,Macho,266,5
4904,ba16888d7,Brumby,2,Macho,299,2
6041,4ec25bc3b,Oshin & Lola,3,Hembra,254,4
8674,97f0a97ef,KANTHAKA,2,Hembra,299,1
11365,f775ef952,J,25,Macho,292,1
14809,437d65d38,No Name,1,Mixto,266,2

In [34]:
df_gatos["Descripcion"] = (df_gatos["Descripcion"].fillna("Sin descripción").str.strip())

#### Verificación final

In [35]:
df_gatos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6861 entries, 0 to 14991
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Nombre                     6861 non-null   object
 1   Edad_Meses                 6861 non-null   int16
 2   Raza_Principal             6861 non-null   int64
 3   Raza_Secundaria            6861 non-null   int64
 4   Genero                     6861 non-null   category
 5   Color_Principal            6861 non-null   int64
 6   Color_Secundario           6861 non-null   int64
 7   Color_Terciario            6861 non-null   int64
 8   Tamano_Madurez             6861 non-null   category
 9   Longitud_Pelo              6861 non-null   category
 10  Vacunado                   6861 non-null   category
 11  Desparasitado              6861 non-null   category
 12  Esterilizado               6861 non-null   category
 13  Salud                      6861 non-null   category
 14  Cantidad                   6861 non-null   int8
 15  Cuota_Adopcion             6861 non-null   int16
 16  Estado                     6861 non-null   int64
 17  ID_Rescatista              6861 non-null   string
 18  Cantidad_Videos            6861 non-null   int8
 19  Descripcion                6861 non-null   string
 20  ID_Mascota                 6861 non-null   string
 21  Cantidad_Fotos             6861 non-null   Int8
 22  Velocidad_Adopcion         6861 non-null   int64
 23  Velocidad_Adopcion_Nombre  6861 non-null   object
dtypes: Int8(1), category(7), int16(2), int64(7), int8(2), object(2), string(3)
memory usage: 798.3+ KB

In [36]:
df_gatos.head()

,Nombre,Edad_Meses,Raza_Principal,Raza_Secundaria,Genero,Color_Principal,Color_Secundario,Color_Terciario,Tamano_Madurez,Longitud_Pelo,...,Cantidad,Cuota_Adopcion,Estado,ID_Rescatista,Cantidad_Videos,Descripcion,ID_Mascota,Cantidad_Fotos,Velocidad_Adopcion,Velocidad_Adopcion_Nombre
0,Nibble,3,299,0,Macho,1,7,0,Pequeño,Corto,...,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1,2,8–30 días
1,No Name Yet,1,265,0,Macho,1,2,0,Mediano,Medio,...,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2,0,Mismo día
5,Sin nombre,3,266,0,Hembra,5,6,0,Mediano,Corto,...,1,0,41326,22fe332bf9c924d4718005891c63fbed,0,This is a stray kitten that came to my house. ...,d24c30b4b,2,2,8–30 días
6,BULAT,12,264,264,Macho,1,0,0,Mediano,Largo,...,1,300,41326,1e0b5a458b5b77f5af581d57ebf570b3,0,anyone within the area of ipoh or taiping who ...,1caa6fcdb,3,1,1–7 días
8,Sin nombre,2,265,0,Hembra,6,0,0,Mediano,Medio,...,1,0,41326,d8af7afece71334473575c9f70daf00d,0,"healthy and active, feisty kitten found in nei...",c06d167ca,6,1,1–7 días

En este notebook se preparó el conjunto de datos de **PetFinder** para su análisis, filtrando únicamente los registros correspondientes a gatos y realizando un proceso de limpieza y estandarización de las variables. Se revisaron los tipos de datos, los valores nulos, las categorías y los rangos de las variables.

Como resultado, se obtendra un archivo **`dataset_gatos_limpio.csv`**, compuesto por **6.861 registros y 24 variables**, listo para utilizarse en posteriores notebooks y en la construcción del dashboard en Power BI.

## Exportación del dataset filtrado

Se guarda el conjunto de datos únicamente con registros de gatos y con las columnas renombradas al español. Este archivo será utilizado en los siguientes notebooks del proyecto.

In [37]:
# Verificar dimensiones finales
print("Dimensiones del dataset limpio:", df_gatos.shape)

# Guardar en CSV
df_gatos.to_csv("dataset_gatos_limpio.csv",index=False,encoding="utf-8-sig")
print("✅ Archivo 'dataset_gatos_limpio.csv' exportado correctamente.")

Dimensiones del dataset limpio: (6861, 24)
✅ Archivo 'dataset_gatos_limpio.csv' exportado correctamente.